version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-chat-bot-postgres
    environment:
      POSTGRES_DB: ai_chat_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - ai-chat-bot-network

  redis:
    image: redis:7-alpine
    container_name: ai-chat-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-chat-bot-network

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    container_name: ai-chat-bot-app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/ai_chat_bot
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - ai-chat-bot-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  ai-chat-bot-network:
    driver: bridge
